import SwiftUI

// GENERATED by ios/tools/plate_art_assets.py — do not edit by hand.
//
// Each entry is a jurisdiction whose tile is drawn from photo-grounded
// artwork in Assets.xcassets/PlateArt rather than from PlateStyle's vector
// motifs. `ink` is the serial color sampled off the real plate, because
// the code and state name on a tile stand in for the serial and should be
// painted the same color the plate paints it. `field` is the color the
// artwork actually puts behind that text — the raster bypasses the vector
// catalogue entirely, so it is the only thing left to audit against.
//
// `halo` marks the handful where the two do not clear WCAG AA. Mostly
// these are honest: New Mexico really is yellow on turquoise and Ontario
// really is white on blue. Rather than repaint a plate into a color it
// does not have, the tile draws those with a soft opposite-luminance ring
// behind the text — which is roughly what the emboss does in daylight.
//
// `scrim` and `offset` are set by hand in the review tool
// (ios/tools/plate_review_server.py), not measured — a human judging the
// art busy enough to dim, or the text sitting somewhere wrong, not a formula.
// `offset` is a fraction of the tile's own width/height, not points, so it
// holds at every size the tile renders at — the Game grid, the trail map pin.
//
// Every jurisdiction has a tile. Yukon was the last without one and is
// the only whose master was drawn from a written description rather than
// against a photograph — Commons has no Yukon plate newer than 1979 — so
// its ink is hand-set in OVERRIDE instead of sampled. No jurisdiction now
// falls through to PlateStyle's vector motifs: they survive only as the
// `?? .fallback` safety net and in PlateBench.
enum PlateArtwork {
    struct Entry {
        let ink: UInt32
        let field: UInt32
        let halo: Bool
        let scrim: Double
        let offsetX: Double
        let offsetY: Double
        /// Opposite luminance to the ink. Precomputed — working it out at
        /// runtime meant three pow() calls per tile per frame.
        let embossHex: UInt32
        /// Interned once here rather than interpolated per body evaluation.
        let asset: String
    }

    static let table: [String: Entry] = [
        "AB": Entry(ink: 0xBD1E24, field: 0xE5E5E6, halo: false, scrim: 0.0, offsetX: -0.001, offsetY: 0.001, embossHex: 0xFFFFFF, asset: "PlateArt/AB"),   // sampled — red with a white outline
        "AK": Entry(ink: 0x262D46, field: 0xE8A606, halo: false, scrim: 0.0, offsetX: -0.016, offsetY: 0.005, embossHex: 0xFFFFFF, asset: "PlateArt/AK"),   // sampled — navy
        "AL": Entry(ink: 0x0A1003, field: 0xFDE081, halo: false, scrim: 0.0, offsetX: 0.02, offsetY: -0.021, embossHex: 0xFFFFFF, asset: "PlateArt/AL"),   // sampled — black
        "AR": Entry(ink: 0x13151A, field: 0xD3D6DE, halo: false, scrim: 0.0, offsetX: -0.014, offsetY: 0.038, embossHex: 0xFFFFFF, asset: "PlateArt/AR"),   // sampled — black
        "AZ": Entry(ink: 0x272729, field: 0xFDFDFD, halo: false, scrim: 0.0, offsetX: 0.007, offsetY: -0.02, embossHex: 0xFFFFFF, asset: "PlateArt/AZ"),   // sampled — near-black
        "BC": Entry(ink: 0x142C54, field: 0xEBE3D3, halo: false, scrim: 0.0, offsetX: 0.007, offsetY: 0.029, embossHex: 0xFFFFFF, asset: "PlateArt/BC"),   // sampled — navy
        "CA": Entry(ink: 0x1D2E4D, field: 0xDFDCDC, halo: false, scrim: 0.0, offsetX: -0.001, offsetY: 0.019, embossHex: 0xFFFFFF, asset: "PlateArt/CA"),   // sampled — navy
        "CO": Entry(ink: 0x0D2C30, field: 0xB6BFC9, halo: false, scrim: 0.0, offsetX: -0.001, offsetY: 0.133, embossHex: 0xFFFFFF, asset: "PlateArt/CO"),   // sampled — dark green
        "CT": Entry(ink: 0x102547, field: 0xE7EBEE, halo: false, scrim: 0.0, offsetX: -0.005, offsetY: 0.003, embossHex: 0xFFFFFF, asset: "PlateArt/CT"),   // sampled — navy
        "DC": Entry(ink: 0x001F8B, field: 0xF1F1F1, halo: false, scrim: 0.0, offsetX: 0.015, offsetY: 0.078, embossHex: 0xFFFFFF, asset: "PlateArt/DC"),   // sampled — navy
        "DE": Entry(ink: 0xC2A54E, field: 0x01073A, halo: false, scrim: 0.0, offsetX: 0.003, offsetY: 0.036, embossHex: 0xFFFFFF, asset: "PlateArt/DE"),   // sampled — gold
        "FL": Entry(ink: 0x1F5C3E, field: 0xE4E4E4, halo: false, scrim: 0.0, offsetX: 0.023, offsetY: 0.04, embossHex: 0xFFFFFF, asset: "PlateArt/FL"),   // blended — embossed green read as grey-green
        "GA": Entry(ink: 0x050504, field: 0xE0E0E0, halo: false, scrim: 0.0, offsetX: 0.0, offsetY: 0.0, embossHex: 0xFFFFFF, asset: "PlateArt/GA"),   // sampled — black
        "HI": Entry(ink: 0x040405, field: 0xFEFEFE, halo: false, scrim: 0.0, offsetX: 0.0, offsetY: 0.0, embossHex: 0xFFFFFF, asset: "PlateArt/HI"),   // sampled — black
        "IA": Entry(ink: 0x1E1E1E, field: 0xFBF8EE, halo: false, scrim: 0.0, offsetX: 0.003, offsetY: 0.036, embossHex: 0xFFFFFF, asset: "PlateArt/IA"),   // blended — read as olive-grey
        "ID": Entry(ink: 0x08090A, field: 0xFEFEFE, halo: false, scrim: 0.0, offsetX: 0.017, offsetY: 0.009, embossHex: 0xFFFFFF, asset: "PlateArt/ID"),   // sampled — black
        "IL": Entry(ink: 0x8C1F2E, field: 0xEFEAE5, halo: false, scrim: 0.0, offsetX: 0.001, offsetY: 0.057, embossHex: 0xFFFFFF, asset: "PlateArt/IL"),   // blended — red glyph over the blue gradient read as plum
        "IN": Entry(ink: 0x252868, field: 0xFBFDFE, halo: false, scrim: 0.0, offsetX: 0.01, offsetY: -0.077, embossHex: 0xFFFFFF, asset: "PlateArt/IN"),   // sampled — navy
        "KS": Entry(ink: 0x040303, field: 0xF5EBD4, halo: false, scrim: 0.0, offsetX: 0.0, offsetY: 0.0, embossHex: 0xFFFFFF, asset: "PlateArt/KS"),   // sampled — black
        "KY": Entry(ink: 0x21679F, field: 0xFBFAF9, halo: true , scrim: 0.0, offsetX: 0.009, offsetY: -0.028, embossHex: 0xFFFFFF, asset: "PlateArt/KY"),   // sampled — navy
        "LA": Entry(ink: 0x0D1012, field: 0xFDEDCB, halo: false, scrim: 0.14, offsetX: 0.006, offsetY: -0.007, embossHex: 0xFFFFFF, asset: "PlateArt/LA"),   // sampled — black
        "MA": Entry(ink: 0xC8292C, field: 0xEBEBEB, halo: false, scrim: 0.0, offsetX: 0.018, offsetY: 0.067, embossHex: 0xFFFFFF, asset: "PlateArt/MA"),   // sampled — red
        "MB": Entry(ink: 0x1C1F43, field: 0xF8F0E5, halo: false, scrim: 0.0, offsetX: 0.025, offsetY: -0.098, embossHex: 0xFFFFFF, asset: "PlateArt/MB"),   // sampled — navy
        "MD": Entry(ink: 0x151110, field: 0xF3F3F3, halo: false, scrim: 0.32, offsetX: -0.003, offsetY: -0.076, embossHex: 0xFFFFFF, asset: "PlateArt/MD"),   // sampled — black
        "ME": Entry(ink: 0x152F48, field: 0xFEFEFE, halo: false, scrim: 0.0, offsetX: 0.0, offsetY: 0.0, embossHex: 0xFFFFFF, asset: "PlateArt/ME"),   // sampled — navy
        "MI": Entry(ink: 0x0842A8, field: 0xF0F0F0, halo: false, scrim: 0.0, offsetX: -0.005, offsetY: 0.043, embossHex: 0xFFFFFF, asset: "PlateArt/MI"),   // sampled — blue
        "MN": Entry(ink: 0x030202, field: 0xF1F1F1, halo: false, scrim: 0.0, offsetX: -0.001, offsetY: 0.089, embossHex: 0xFFFFFF, asset: "PlateArt/MN"),   // sampled — black
        "MO": Entry(ink: 0x072D69, field: 0xF3F1ED, halo: false, scrim: 0.0, offsetX: 0.0, offsetY: 0.0, embossHex: 0xFFFFFF, asset: "PlateArt/MO"),   // sampled — blue
        "MS": Entry(ink: 0x26365E, field: 0xE1E4E5, halo: false, scrim: 0.0, offsetX: 0.0, offsetY: 0.092, embossHex: 0xFFFFFF, asset: "PlateArt/MS"),   // blended — read as slate
        "MT": Entry(ink: 0x414856, field: 0xC4E1F8, halo: false, scrim: 0.0, offsetX: 0.02, offsetY: 0.065, embossHex: 0xFFFFFF, asset: "PlateArt/MT"),   // sampled — dark grey
        "NB": Entry(ink: 0x9E2A42, field: 0xF0F4F8, halo: false, scrim: 0.0, offsetX: 0.008, offsetY: 0.069, embossHex: 0xFFFFFF, asset: "PlateArt/NB"),   // sampled — deep red
        "NC": Entry(ink: 0x0E25A0, field: 0xF6F3EA, halo: false, scrim: 0.0, offsetX: 0.038, offsetY: 0.082, embossHex: 0xFFFFFF, asset: "PlateArt/NC"),   // sampled — deep blue
        "ND": Entry(ink: 0x12181B, field: 0x72ADD5, halo: false, scrim: 0.0, offsetX: 0.003, offsetY: 0.014, embossHex: 0xFFFFFF, asset: "PlateArt/ND"),   // sampled — black
        "NE": Entry(ink: 0x1A1F5B, field: 0xF8F9FC, halo: false, scrim: 0.0, offsetX: 0.001, offsetY: 0.056, embossHex: 0xFFFFFF, asset: "PlateArt/NE"),   // sampled — navy
        "NH": Entry(ink: 0x143A32, field: 0xCCCCC6, halo: false, scrim: 0.0, offsetX: 0.009, offsetY: 0.015, embossHex: 0xFFFFFF, asset: "PlateArt/NH"),   // sampled — dark green
        "NJ": Entry(ink: 0x151318, field: 0xFCE9B8, halo: false, scrim: 0.0, offsetX: 0.01, offsetY: 0.066, embossHex: 0xFFFFFF, asset: "PlateArt/NJ"),   // sampled — black
        "NL": Entry(ink: 0x0D136C, field: 0xFEFAF2, halo: false, scrim: 0.0, offsetX: 0.015, offsetY: 0.049, embossHex: 0xFFFFFF, asset: "PlateArt/NL"),   // sampled — deep blue
        "NM": Entry(ink: 0xE6BF3C, field: 0x0494AA, halo: true , scrim: 0.0, offsetX: -0.001, offsetY: 0.01, embossHex: 0x000000, asset: "PlateArt/NM"),   // sampled — yellow
        "NS": Entry(ink: 0x1A3D99, field: 0xFAF6F1, halo: false, scrim: 0.0, offsetX: 0.014, offsetY: 0.203, embossHex: 0xFFFFFF, asset: "PlateArt/NS"),   // sampled — blue
        "NT": Entry(ink: 0x143063, field: 0xD5EDF6, halo: false, scrim: 0.0, offsetX: -0.002, offsetY: 0.046, embossHex: 0xFFFFFF, asset: "PlateArt/NT"),   // sampled — navy
        "NU": Entry(ink: 0x1C1C1C, field: 0xFBF8F2, halo: false, scrim: 0.16, offsetX: 0.007, offsetY: 0.034, embossHex: 0xFFFFFF, asset: "PlateArt/NU"),   // blended — read as mid grey
        "NV": Entry(ink: 0x141113, field: 0x71ACE6, halo: false, scrim: 0.08, offsetX: 0.017, offsetY: 0.08, embossHex: 0xFFFFFF, asset: "PlateArt/NV"),   // sampled — black
        "NY": Entry(ink: 0x1F2A45, field: 0xFCF0D9, halo: false, scrim: 0.0, offsetX: 0.011, offsetY: 0.032, embossHex: 0xFFFFFF, asset: "PlateArt/NY"),   // blended — read as near-black; the plate is navy
        "OH": Entry(ink: 0xC1272D, field: 0xEBF2FC, halo: false, scrim: 0.0, offsetX: 0.009, offsetY: 0.015, embossHex: 0xFFFFFF, asset: "PlateArt/OH"),   // no serial — template shows the wordmark only; serial is red
        "OK": Entry(ink: 0xFFFBFD, field: 0xA91F23, halo: false, scrim: 0.0, offsetX: 0.018, offsetY: 0.124, embossHex: 0x000000, asset: "PlateArt/OK"),   // sampled — white
        "ON": Entry(ink: 0x003A8B, field: 0xEBE9EA, halo: false, scrim: 0.0, offsetX: 0.005, offsetY: 0.141, embossHex: 0xFFFFFF, asset: "PlateArt/ON"),   // sampled — blue
        "OR": Entry(ink: 0x24304C, field: 0xD1CEE2, halo: false, scrim: 0.0, offsetX: 0.011, offsetY: 0.124, embossHex: 0xFFFFFF, asset: "PlateArt/OR"),   // blended — read as charcoal; the plate is navy
        "PA": Entry(ink: 0x092550, field: 0xFEFEFE, halo: false, scrim: 0.0, offsetX: 0.008, offsetY: 0.046, embossHex: 0xFFFFFF, asset: "PlateArt/PA"),   // sampled — navy
        "PE": Entry(ink: 0x138142, field: 0xFEFEFE, halo: false, scrim: 0.0, offsetX: 0.006, offsetY: 0.164, embossHex: 0xFFFFFF, asset: "PlateArt/PE"),   // sampled — green
        "PR": Entry(ink: 0x111114, field: 0xBBDBF4, halo: true , scrim: 0.0, offsetX: -0.0, offsetY: 0.106, embossHex: 0xFFFFFF, asset: "PlateArt/PR"),   // sampled — black
        "QC": Entry(ink: 0x16277A, field: 0xFEFEFE, halo: false, scrim: 0.0, offsetX: -0.001, offsetY: 0.109, embossHex: 0xFFFFFF, asset: "PlateArt/QC"),   // no serial — blank template, color taken from the wordmark
        "RI": Entry(ink: 0x023564, field: 0xDBEEF9, halo: false, scrim: 0.0, offsetX: 0.001, offsetY: 0.074, embossHex: 0xFFFFFF, asset: "PlateArt/RI"),   // sampled — navy
        "SC": Entry(ink: 0x0F1414, field: 0xF9F6F0, halo: false, scrim: 0.0, offsetX: -0.007, offsetY: 0.157, embossHex: 0xFFFFFF, asset: "PlateArt/SC"),   // pinned — the tile keeps the pre-2026 palmetto base; see the note above
        "SD": Entry(ink: 0x0F161F, field: 0xBCD4E6, halo: false, scrim: 0.12, offsetX: 0.031, offsetY: 0.029, embossHex: 0xFFFFFF, asset: "PlateArt/SD"),   // sampled — black
        "SK": Entry(ink: 0x105C56, field: 0xF9F1E1, halo: false, scrim: 0.0, offsetX: 0.011, offsetY: 0.096, embossHex: 0xFFFFFF, asset: "PlateArt/SK"),   // sampled — green
        "TN": Entry(ink: 0xFFFFFF, field: 0x14204C, halo: false, scrim: 0.0, offsetX: 0.001, offsetY: 0.023, embossHex: 0x000000, asset: "PlateArt/TN"),   // no serial — blank template; white on navy
        "TX": Entry(ink: 0x040404, field: 0xEDEDED, halo: false, scrim: 0.0, offsetX: 0.005, offsetY: 0.027, embossHex: 0xFFFFFF, asset: "PlateArt/TX"),   // sampled — black
        "UT": Entry(ink: 0x10254D, field: 0xEA642C, halo: false, scrim: 0.5, offsetX: 0.0, offsetY: 0.021, embossHex: 0xFFFFFF, asset: "PlateArt/UT"),   // sampled — navy
        "VA": Entry(ink: 0x0E254A, field: 0xEFEFED, halo: false, scrim: 0.0, offsetX: -0.0, offsetY: -0.007, embossHex: 0xFFFFFF, asset: "PlateArt/VA"),   // sampled — navy
        "VT": Entry(ink: 0x0B6647, field: 0xEFEFEF, halo: false, scrim: 0.0, offsetX: 0.003, offsetY: 0.02, embossHex: 0xFFFFFF, asset: "PlateArt/VT"),   // inverted — art is green-on-white, so the serial is green
        "WA": Entry(ink: 0x222A38, field: 0xF9EEDB, halo: false, scrim: 0.0, offsetX: 0.001, offsetY: 0.051, embossHex: 0xFFFFFF, asset: "PlateArt/WA"),   // sampled — navy
        "WI": Entry(ink: 0x21272A, field: 0xFEFEFE, halo: false, scrim: 0.0, offsetX: 0.022, offsetY: 0.094, embossHex: 0xFFFFFF, asset: "PlateArt/WI"),   // sampled — black
        "WV": Entry(ink: 0x112356, field: 0xF9F7F6, halo: false, scrim: 0.0, offsetX: 0.013, offsetY: 0.035, embossHex: 0xFFFFFF, asset: "PlateArt/WV"),   // sampled — navy
        "WY": Entry(ink: 0xF0EEE5, field: 0x293857, halo: true , scrim: 0.0, offsetX: 0.0, offsetY: 0.0, embossHex: 0x000000, asset: "PlateArt/WY"),   // sampled — white
        "YT": Entry(ink: 0x1A1A1A, field: 0xEDEDEB, halo: false, scrim: 0.0, offsetX: 0.001, offsetY: -0.007, embossHex: 0xFFFFFF, asset: "PlateArt/YT"),   // no photograph — 'black on reflective white' is the whole source; see PROMPTS['YT'] in plate_art_generate.py
    ]

    static func has(_ code: String) -> Bool { table[code] != nil }

    /// The asset name. Namespaced by the PlateArt folder in the catalogue.
    static func imageName(_ code: String) -> String {
        table[code]?.asset ?? "PlateArt/\(code)"
    }

    /// The serial color, when this plate has artwork.
    static func ink(_ code: String) -> Color? {
        table[code].map { Color(hex: $0.ink) }
    }

    /// The ring drawn behind the text, on the four plates whose own two
    /// colors do not clear WCAG AA.
    ///
    /// Every plate used to get a faint one too, on the theory that two lines
    /// of type could not fit inside the artwork's clear band. The review pass
    /// then moved the block by hand on 60 of the 63, which is the real fix —
    /// and a blurred shadow is an offscreen render pass per tile per frame,
    /// which at 65 tiles is what made the grid stutter. So it is now only
    /// where it is doing load-bearing work.
    static func halo(_ code: String) -> Color? {
        guard let e = table[code], e.halo else { return nil }
        return Color(hex: e.embossHex)
    }

    /// The scrim's color — the same opposite-luminance value the halo uses,
    /// so turning the dim up deepens one effect rather than adding a second.
    static func scrimColor(_ code: String) -> Color? {
        guard let e = table[code], e.scrim > 0 else { return nil }
        return Color(hex: e.embossHex)
    }

    /// How much to dim the art behind the text, 0...0.8. Set per-plate in
    /// the review tool for designs busy enough that the emboss alone isn't
    /// enough — South Dakota's Rushmore photo, Nunavut's aurora.
    static func scrim(_ code: String) -> Double {
        table[code]?.scrim ?? 0
    }

    /// Where to place the code/name block, as a fraction of the tile's own
    /// width (x) and height (y) from centre — (0, 0) is dead centre, matching
    /// what every plate does until the review tool moves it.
    static func offset(_ code: String) -> (x: Double, y: Double) {
        guard let e = table[code] else { return (0, 0) }
        return (e.offsetX, e.offsetY)
    }
}
